# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='取引先名')),
                ('trade_division_id', models.IntegerField(blank=True, default=0, verbose_name='取引区分ID')),
                ('payment_subject_id', models.IntegerField(blank=True, default=0, verbose_name='支払科目ID')),
                ('account_title_id', models.IntegerField(blank=True, default=0, verbose_name='支払方法ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='振込先銀行名')),
                ('branch_name', models.CharField(max_length=255, verbose_name='振込先支店名')),
                ('account_type', models.IntegerField(blank=True, default=0, verbose_name='口座種別')),
                ('account_number', models.IntegerField(blank=True, default=0, verbose_name='口座番号')),
            ],
        ),
    ]
