# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-06 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='勘定科目名')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='account_title_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='支払科目ID'),
        ),
		migrations.RemoveField(
            model_name='partner',
            name='payment_subject_id',
        ),
		migrations.AddField(
            model_name='partner',
            name='payment_method_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='支払方法ID'),
        ),
    ]
