# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-24 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_flow_detail_expected',
            name='account_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account_Title', verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='cash_flow_detail_expected',
            name='cash_id',
            field=models.IntegerField(default=None, null=True, verbose_name='現金Id'),
        ),
    ]
