# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-06 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180106_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttitle',
            name='trade_division_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='取引区分ID'),
        ),
    ]
