# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accounttitle_trade_division_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='pay_day',
            field=models.IntegerField(blank=True, default=0, verbose_name='支払日'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_flag',
            field=models.IntegerField(default=0, verbose_name='支払月フラグ'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_1',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ１月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_10',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ１０月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_11',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ１１月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_12',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ１２月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_2',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ２月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_3',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ３月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_4',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ４月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_5',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ５月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_6',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ６月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_7',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ７月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_8',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ８月'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_month_flag_9',
            field=models.BooleanField(default=False, verbose_name='支払月フラグ９月'),
        ),
        migrations.AlterField(
            model_name='accounttitle',
            name='trade_division_id',
            field=models.IntegerField(blank=True, choices=[(0, '経費'), (1, '外注・工事仕入')], default=0, verbose_name='取引区分(0:経費 1:外注等)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='account_type',
            field=models.IntegerField(blank=True, choices=[(0, '普通'), (1, '当座')], default=0, verbose_name='口座種別'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='trade_division_id',
            field=models.IntegerField(blank=True, choices=[(0, '経費'), (1, '外注・工事仕入')], default=0, verbose_name='取引区分ID'),
        ),
    ]
