# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-25 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180125_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='pay_flag',
        ),
        migrations.AddField(
            model_name='partner',
            name='pay_day_division',
            field=models.IntegerField(choices=[(0, '当月'), (1, '翌月'), (2, '月末')], default=0, verbose_name='支払フラグ(月末等)'),
        ),
    ]
