# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-16 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180125_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='銀行名')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.IntegerField(default=0, verbose_name='銀行ID')),
                ('name', models.CharField(max_length=255, verbose_name='銀行支店名')),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_day_division',
            field=models.IntegerField(choices=[(0, '当月'), (1, '翌月'), (2, '翌々月'), (3, '月末')], default=0, verbose_name='支払フラグ(月末等)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_1',
            field=models.BooleanField(default=False, verbose_name='１月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_10',
            field=models.BooleanField(default=False, verbose_name='１０月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_11',
            field=models.BooleanField(default=False, verbose_name='１１月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_12',
            field=models.BooleanField(default=False, verbose_name='１２月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_2',
            field=models.BooleanField(default=False, verbose_name='２月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_3',
            field=models.BooleanField(default=False, verbose_name='３月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_4',
            field=models.BooleanField(default=False, verbose_name='４月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_5',
            field=models.BooleanField(default=False, verbose_name='５月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_6',
            field=models.BooleanField(default=False, verbose_name='６月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_7',
            field=models.BooleanField(default=False, verbose_name='７月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_8',
            field=models.BooleanField(default=False, verbose_name='８月'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_month_flag_9',
            field=models.BooleanField(default=False, verbose_name='９月'),
        ),
    ]
