# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-17 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180216_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='bank_branch_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='振込先銀行'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='振込先銀行'),
        ),
        migrations.AlterField(
            model_name='bank_branch',
            name='bank_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='銀行ID'),
        ),
    ]
