# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_balance_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_sheet',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='適用'),
        ),
    ]
