# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200124_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='cash_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Cash_Book', verbose_name='出納帳'),
        ),
        migrations.AlterField(
            model_name='balance_sheet',
            name='bank_id',
            field=models.IntegerField(blank=True, choices=[(0, '北越'), (1, 'さんしん(塚野目)'), (2, 'さんしん(本店)')], default=None, null=True, verbose_name='銀行Id'),
        ),
        migrations.AlterField(
            model_name='balance_sheet',
            name='borrow_lend_id',
            field=models.IntegerField(choices=[(0, '貸'), (1, '借')], default=0, verbose_name='貸借Id'),
        ),
    ]
