# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-19 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180217_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='bank_branch_id',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='partner',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Bank', verbose_name='振込先銀行'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Bank_Branch', verbose_name='振込先支店名'),
        ),
        migrations.AlterField(
            model_name='bank_branch',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Bank', verbose_name='銀行名'),
        ),
    ]
