# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-25 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200124_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Sheet_Tally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_date', models.DateField(blank=True, null=True, verbose_name='発生日')),
                ('borrow_amount', models.IntegerField(blank=True, default=0, verbose_name='貸金額')),
                ('lend_amount', models.IntegerField(blank=True, default=0, verbose_name='借金額')),
            ],
        ),
    ]
