# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-27 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_cash_flow_detail_actual_cash_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_flow_detail_actual',
            name='construction_id',
        ),
    ]
