# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180220_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fixed_cost',
            field=models.BooleanField(default=False, verbose_name='固定費'),
        ),
    ]
