# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_cash_flow_detail_actual_construction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_sheet',
            name='account_id',
        ),
        migrations.AddField(
            model_name='balance_sheet',
            name='account_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account_Title', verbose_name='科目'),
        ),
    ]
