# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-20 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180220_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trade_division_id',
            field=models.IntegerField(blank=True, choices=[(0, '経費'), (1, '外注・工事仕入')], null=True, verbose_name='取引区分ID'),
        ),
    ]
