# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180228_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='administrative_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='取引先名(管理用)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='payment_method_id',
            field=models.IntegerField(blank=True, choices=[(0, '口座振替'), (1, '振込'), (2, '現金')], default=0, verbose_name='支払方法ID'),
        ),
    ]
