# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-31 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_cash_flow_detail_expected_payment_method_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'construction_data',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='cash_flow_detail_expected',
            name='construction_id',
        ),
        migrations.AlterField(
            model_name='balance_sheet',
            name='bank_id',
            field=models.IntegerField(blank=True, choices=[('', '-'), (0, '北越'), (1, 'さんしん(塚野目)'), (2, 'さんしん(本店)')], default=None, null=True, verbose_name='銀行Id'),
        ),
        migrations.AddField(
            model_name='cash_flow_detail_expected',
            name='construction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.ConstructionData', verbose_name='工事Id'),
        ),
    ]
