# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_partner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='fixed_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='固定費'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rough_estimate',
            field=models.IntegerField(blank=True, null=True, verbose_name='概算'),
        ),
    ]
