# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180228_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='account_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='口座番号'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='account_type',
            field=models.IntegerField(blank=True, choices=[(0, '普通'), (1, '当座')], null=True, verbose_name='口座種別'),
        ),
    ]
