# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-02-01 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_cash_flow_detail_actual_payment_method_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_flow_detail_actual',
            name='invoice_header_id',
        ),
        migrations.AddField(
            model_name='cash_flow_detail_actual',
            name='invoice_header',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.InvoiceHeader', verbose_name='請求書'),
        ),
    ]
