# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-02 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180228_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='account_type',
            field=models.IntegerField(blank=True, choices=[('', 'None'), (0, '普通'), (1, '当座')], null=True, verbose_name='口座種別'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='fixed_content_id',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, '項目のみ'), (2, '項目のみ（指定月）'), (3, '項目・固定費'), (4, '項目・固定費（指定月）'), (5, '項目・概算＝仕入金額')], null=True, verbose_name='固定項目フラグ'),
        ),
    ]
