# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-05-07 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200507_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='unpayment_amount',
            new_name='unpaid_amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='unpayment_date',
            new_name='unpaid_date',
        ),
    ]
