# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-02 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180302_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='ソート順'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='account_type',
            field=models.IntegerField(blank=True, choices=[('', '-'), (0, '普通'), (1, '当座')], null=True, verbose_name='口座種別'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='fixed_content_id',
            field=models.IntegerField(blank=True, choices=[(0, '項目のみ'), (1, '項目のみ（指定月）'), (2, '項目・固定費'), (3, '項目・固定費（指定月）'), (4, '項目・概算＝仕入金額')], null=True, verbose_name='固定項目フラグ'),
        ),
    ]
