# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-03 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20180302_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='account_title_id',
        ),
        migrations.AddField(
            model_name='partner',
            name='account_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account_Title', verbose_name='支払科目'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='account_type',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, '普通'), (2, '当座')], null=True, verbose_name='口座種別'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='fixed_content_id',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, '項目のみ'), (2, '項目のみ（指定月）'), (3, '項目・固定費'), (4, '項目・固定費（指定月）'), (5, '項目・概算＝仕入金額')], null=True, verbose_name='固定項目フラグ'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='payment_method_id',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, '口座振替'), (2, '振込'), (3, '現金')], default=0, verbose_name='支払方法ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method_id',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, '口座振替'), (2, '振込'), (3, '現金')], default=0, verbose_name='支払方法'),
        ),
    ]
