# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2023-01-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20230127_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='completed_flag',
            field=models.IntegerField(choices=[(0, '未払'), (1, '完了')], default=0, verbose_name='完了フラグ'),
        ),
    ]
