# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180303_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rough_estimate',
            field=models.IntegerField(blank=True, null=True, verbose_name='概算'),
        ),
    ]
