# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-05 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_payment_rough_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fixed_cost',
        ),
        migrations.AlterField(
            model_name='account_title',
            name='trade_division_id',
            field=models.IntegerField(blank=True, choices=[(0, '外注・工事仕入'), (1, '経費')], default=0, verbose_name='取引区分(0:経費 1:外注等)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='payment_method_id',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, '振込'), (2, '口座振替'), (3, '現金')], default=0, verbose_name='支払方法ID'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='trade_division_id',
            field=models.IntegerField(blank=True, choices=[(0, '外注・工事仕入'), (1, '経費')], default=0, verbose_name='取引区分ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method_id',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, '振込'), (2, '口座振替'), (3, '現金')], default=0, verbose_name='支払方法'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trade_division_id',
            field=models.IntegerField(blank=True, choices=[(0, '外注・工事仕入'), (1, '経費')], null=True, verbose_name='取引区分ID'),
        ),
    ]
