# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2023-04-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20230128_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_type_id', models.IntegerField(blank=True, null=True, verbose_name='テーブル種類ID')),
                ('table_id', models.IntegerField(blank=True, null=True, verbose_name='テーブルID')),
                ('deposit_due_date', models.DateField(verbose_name='入金予定日')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('deposit_amount', models.IntegerField(blank=True, null=True, verbose_name='入金金額')),
                ('deposit_source_id', models.IntegerField(blank=True, null=True, verbose_name='入金先ID')),
                ('completed_flag', models.IntegerField(blank=True, null=True, verbose_name='完了フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'deposits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_type_id', models.IntegerField(blank=True, null=True, verbose_name='テーブル種類ID')),
                ('table_id', models.IntegerField(blank=True, null=True, verbose_name='テーブルID')),
                ('payment_method_id', models.IntegerField(blank=True, null=True, verbose_name='支払方法ID')),
                ('payment_on', models.DateField(verbose_name='支払日')),
                ('unpaid_on', models.DateField(verbose_name='未払支払日')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('payment_amount', models.IntegerField(blank=True, null=True, verbose_name='支払金額')),
                ('unpaid_amount', models.IntegerField(blank=True, null=True, verbose_name='未払金額')),
                ('billing_year_month', models.DateField(verbose_name='支払月')),
                ('payment_source_id', models.IntegerField(blank=True, null=True, verbose_name='支払元ID')),
                ('is_estimate', models.IntegerField(blank=True, null=True, verbose_name='概算フラグ')),
                ('is_completed', models.IntegerField(blank=True, null=True, verbose_name='完了フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'expences',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='cash_book',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_partner', to='account.Partner', verbose_name='取引先(連携用)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='unpaid_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='未払支払予定日'),
        ),
        migrations.AddField(
            model_name='payment_reserve',
            name='completed_flag',
            field=models.IntegerField(choices=[(0, '未払'), (1, '完了')], default=0, verbose_name='完了フラグ'),
        ),
        migrations.AddField(
            model_name='payment_reserve',
            name='unpaid_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='未払支払予定日'),
        ),
    ]
