# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-06 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20180306_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='billing_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='支払金額'),
        ),
    ]
