# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-06 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20180306_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_title',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='ソート順'),
        ),
        migrations.AddField(
            model_name='bank_branch',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='ソート順'),
        ),
    ]
