# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2023-11-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20231122_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='description2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='摘要2'),
        ),
        migrations.AddField(
            model_name='balance_sheet',
            name='is_representative',
            field=models.BooleanField(default=False, verbose_name='代表者貸付'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_due_date_changed',
            field=models.DateField(blank=True, null=True, verbose_name='支払予定変更日'),
        ),
        migrations.AddField(
            model_name='payment_reserve',
            name='unpaid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='未払金額'),
        ),
        migrations.AddField(
            model_name='payment_reserve',
            name='unpaid_date',
            field=models.DateField(blank=True, null=True, verbose_name='未払支払日'),
        ),
        migrations.AlterField(
            model_name='balance_sheet',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='staff',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Staff', verbose_name='担当者(社長以外)'),
        ),
    ]
