# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2023-11-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20231127_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_book',
            name='is_representative',
            field=models.BooleanField(default=False, verbose_name='代表者貸付'),
        ),
    ]
