# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-06 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20180306_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='ソート順'),
        ),
    ]
