# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='payment_method_id',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, '振込'), (2, '口座振替'), (3, '現金')], null=True, verbose_name='支払方法ID'),
        ),
    ]
