# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2024-03-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='ソート順')),
                ('name', models.CharField(max_length=255, verbose_name='補助科目名')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account', verbose_name='勘定科目名')),
            ],
        ),
    ]
