# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2024-04-26 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20240315_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_representative_loan',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='daily_representative_loan',
            name='sub_account_id',
        ),
        migrations.AddField(
            model_name='daily_representative_loan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account', verbose_name='科目'),
        ),
        migrations.AddField(
            model_name='daily_representative_loan',
            name='account_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account_Sub', verbose_name='補助'),
        ),
    ]
