# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2024-04-27 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20240426_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_representative_loan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
