# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2024-05-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20240427_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Representative_Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_year_month', models.DateField(verbose_name='発生年月')),
                ('last_month_balance', models.IntegerField(blank=True, null=True, verbose_name='前月残')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
        ),
    ]
