# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20180312_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='口座番号'),
        ),
    ]
