# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20180323_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='source_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_bank', to='account.Bank', verbose_name='振込/振替元'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pay_day_division',
            field=models.IntegerField(choices=[(0, '当月'), (1, '翌月'), (2, '翌々月'), (3, '月末(休日前倒し)'), (4, '月末(休日先送り)')], default=0, verbose_name='支払フラグ(月末等)'),
        ),
    ]
