# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20180417_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='手数料'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='支払金額'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='source_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_bank', to='account.Bank', verbose_name='振込/振替元銀行'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='請求金額'),
        ),
    ]
