# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-17 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_auto_20180418_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_source_bank', to='account.Bank', verbose_name='振込/振替元銀行'),
        ),
    ]
