# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-28 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_payment_source_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cash_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='精算日')),
                ('description_partner', models.CharField(max_length=255, verbose_name='適用(取引先)')),
                ('description_content', models.CharField(max_length=255, verbose_name='適用(取引内容)')),
                ('incomes', models.IntegerField(blank=True, null=True, verbose_name='収入金額')),
                ('expences', models.IntegerField(blank=True, null=True, verbose_name='支払金額')),
                ('balance', models.IntegerField(blank=True, null=True, verbose_name='差引残高')),
                ('account_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_account_title', to='account.Account_Title', verbose_name='支払科目')),
                ('staff', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Staff')),
            ],
        ),
        migrations.AlterField(
            model_name='bank_branch',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Bank', verbose_name='銀行名'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='account_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account_Title', verbose_name='支払科目'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Bank', verbose_name='振込先銀行'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Bank_Branch', verbose_name='振込先支店名'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='source_bank',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_bank', to='account.Bank', verbose_name='振込/振替元銀行'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account_Title', verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Partner', verbose_name='取引先'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_source_bank', to='account.Bank', verbose_name='振込/振替元銀行'),
        ),
    ]
