# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-06 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20180501_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_book',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='領収書日付'),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='description_content',
            field=models.CharField(blank=True, max_length=255, verbose_name='摘要(取引内容)'),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='description_partner',
            field=models.CharField(blank=True, max_length=255, verbose_name='摘要(取引先)'),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='purchase_order_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.PurchaseOrderData', verbose_name='注文Ｎｏ'),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='staff',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Staff', verbose_name='担当者'),
        ),
    ]
