# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20180507_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Book_Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computation_date', models.DateField(verbose_name='集計日')),
                ('balance', models.IntegerField(blank=True, null=True, verbose_name='残高')),
                ('balance_president', models.IntegerField(blank=True, null=True, verbose_name='残高(社長)')),
                ('balance_staff', models.IntegerField(blank=True, null=True, verbose_name='残高(社員)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.AddField(
            model_name='cash_book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='cash_book',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
