# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-11 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_auto_20180508_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_book',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='ソート順'),
        ),
    ]
