import account.views.views
import account.views.ajaxs
import account.views.pdf_payment_list
import account.views.pdf_cash_flow_list
import account.views.pdf_cash_book
import account.views.data_transfer
import account.views.aggregate_weekly
import account.views.aggregate_cash_flow
import account.views.aggregate_balance_sheet
import account.views.export_csv
import account.views.machine_learning
import account.views.set_cash_flow_detail
import account.views.set_cash_book_to_balance_sheet
